version: "3.8"

services:
    db:
        container_name: postgres-taskmanager
        image: postgres:16.0-alpine
        restart: always
        environment:
            - POSTGRES_USER=${TYPEORM_USERNAME}
            - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
            - POSTGRES_DB=${TYPEORM_DATABASE}
        volumes:
            - ./volumes/pgdata:/var/lib/postgresql/data
        ports:
            - ${TYPEORM_PORT}:${TYPEORM_PORT}
