version: "3.8"

services:
    db:
        container_name: postgres-taskmanager
        image: postgres:16.0-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123123
            - POSTGRES_DB=taskmanager
        volumes:
            - ./volumes/pgdata:/var/lib/postgresql/data
        ports:
            - ${TYPEORM_PORT}:${TYPEORM_PORT}
